//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BucketList.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Challenge
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Challenge()
        {
            this.Ratings = new HashSet<Rating>();
            this.UserChallenges = new HashSet<UserChallenge>();
        }
    
        public int challengeID { get; set; }
        public string title { get; set; }
        public string description { get; set; }
        public Nullable<int> difficulty { get; set; }
        public Nullable<int> points { get; set; }
        public Nullable<bool> needPhoto { get; set; }
        public Nullable<bool> canBeGroup { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rating> Ratings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserChallenge> UserChallenges { get; set; }
    }
}
