//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BucketList.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GroupChallengeInvite
    {
        public int challengeInviteID { get; set; }
        public int fromUserID { get; set; }
        public int toUserID { get; set; }
        public int challengeID { get; set; }
        public string status { get; set; }
    
        public virtual User User { get; set; }
        public virtual UserChallenge UserChallenge { get; set; }
    }
}
