//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BucketList.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DatabaseEntities1 : DbContext
    {
        public DatabaseEntities1()
            : base("name=DatabaseEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Achievement> Achievements { get; set; }
        public virtual DbSet<Challenge> Challenges { get; set; }
        public virtual DbSet<FriendInvite> FriendInvites { get; set; }
        public virtual DbSet<Friendship> Friendships { get; set; }
        public virtual DbSet<GroupChallengeInvite> GroupChallengeInvites { get; set; }
        public virtual DbSet<Rating> Ratings { get; set; }
        public virtual DbSet<SuggestedChallenge> SuggestedChallenges { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UserChallenge> UserChallenges { get; set; }
    }
}
