//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BucketList.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SuggestedChallenge
    {
        public int suggestedChallengeID { get; set; }
        public Nullable<int> userID { get; set; }
        public string title { get; set; }
        public string description { get; set; }
        public Nullable<int> difficulty { get; set; }
        public Nullable<int> points { get; set; }
        public Nullable<bool> needPhoto { get; set; }
        public Nullable<bool> canBeGroup { get; set; }
    
        public virtual User User { get; set; }
    }
}
