//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BucketList.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserChallenge
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserChallenge()
        {
            this.GroupChallengeInvites = new HashSet<GroupChallengeInvite>();
        }
    
        public int userID { get; set; }
        public int challengeID { get; set; }
        public string status { get; set; }
        public string photo { get; set; }
    
        public virtual Challenge Challenge { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GroupChallengeInvite> GroupChallengeInvites { get; set; }
        public virtual User User { get; set; }
    }
}
